# Configuration example to run the DeepEcho Benchmark
# on Kubernetes.
dask_cluster:
  image: sdvproject/deepecho:0.0.3.dev0
  master_resources:
    cpu: 1
    memory: 4G
  worker_resources:
    cpu: 1
    memory: 4G
    nvidia.com/gpu: 1    # Remove or uncomment for no-GPU exeuction
  workers: 1
run:
  args:
    datasets:    # List of datasets to run on
      - Libras
    #   - AtrialFibrillation
    #   - BasicMotions
    #   - ERing
    #   - RacketSports
    #   - Epilepsy
    #   - PenDigits
    #   - JapaneseVowels
    #   - StandWalkJump
    # max_entities: 100   # Maximum number of entities per dataset
    # models:    # List of models to benchmark and arguments
    # -
    #   - PARModel
    #   - epochs: 128
    #     cuda: False
    distributed: True
  function: deepecho.benchmark.run_benchmark
output:
  path: results.csv
  bucket: deepecho-test
  key: AKIAJUR7H5H2UH3FQ7VQ
  secret_key: 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
